repos:
-   repo: local
    hooks:
    -   id: haddock
        entry: ./build-docs.sh
        files: '\.hs$'
        name: haddock
        language: system
    -   id: hlint
        entry: hlint
        files: '\.hs$'
        language: system
        name: hlint
    -   id: stylish-haskell
        entry: stylish-haskell --inplace
        files: '\.hs$'
        name: stylish-haskell
        language: system

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: '\.txt$'
