name: CI

on:
  push:

jobs:
  get-all-days:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls -d ./Day*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')"

  tests:
    needs: get-all-days
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ${{ fromJson(needs.get-all-days.outputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.4.2'

    - run: make test
      working-directory: ${{ matrix.dir }}
